version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
